#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 17 18:47:37 202s3

@author: elisabethburnor
"""

import dyn_model as dyn
import numpy as np
#import pathlib as pathlib
import time as time
import os as os
import pickle as pickle

# Read in csvs
fixed_p = np.loadtxt('Fixed_Params.csv',skiprows = 1, delimiter=",")
dist_p = np.loadtxt('Distributed_Params.csv',skiprows = 1, delimiter=",")
day_p = np.loadtxt('Day_Params.csv',skiprows = 1, delimiter=",")

# These stay the same every run
probShed = np.loadtxt('shedding_probability.csv', skiprows = 1, delimiter=",")
shedDist = np.loadtxt('shedding_distribution.csv',  skiprows = 1, delimiter=",")

# Create filepath for folder where results will go
run_savepath = '/filepath/'

# Set up water system
# WaterSystem(fixParams,distParams,dayParams, shedding, samVol, sens, bactNum)
    
ws = dyn.WaterSystem(fixParams= fixed_p, distParams = dist_p, dayParams = day_p, probShed = probShed, sheddingDist = shedDist, samVol = 6, sens = 0.83, bactNum = 1, savePath = run_savepath, resolution = 10)
 
start_run = time.time()
ws.run(3,1000)
stop_run = time.time()
print("one run", stop_run-start_run)

ws.createCSV('run')
ws.graphByHour(saveFile = True)
ws.graphByBranch(saveFile = True)
ws.graphByBranchConc(saveFile = True)
    
ws.graphDetectByBranchSection(573, 0, saveFile = False)
ws.graphDetectByBranchSection(815, 5, saveFile = True)
ws.graphDetectByBranchSection(850, 0, saveFile = True)
ws.graphDetectByBranchSection(912, 0, saveFile = True)
ws.graphDetectByBranchSection(937, 9, saveFile = True)
     
 # Save model 
with open("store_ws.py", 'wb') as system_save:
    pickle.dump(ws, system_save)
    


